spring:
  application:
    name: YunaNexus-AuthService
  data:
    redis:
      host: 127.0.0.1
      port: 6379

# MyBatisPlus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cc.nanoic.yunanexus.auth.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

# 服务默认端口
server:
  port: 8200

#
yunanexus:
  auth:
    builtin-clients: # 初始化构建参数
      - client-name: YunaNexusWeb
        client-type: 1
        scope: core:*:*:*
        grant-types: password,refresh_token
        redirect-uri: ${YUNANEXUS_WEB_URL}
    jwt:
      secret: ${YUNANEXUS_AUTH_JWT_SECRET}
      access-exp: 7200 # AccessToken 2小时
      refresh-exp: 604800 # RefreshToken 7天
    rsa:
      key-path: ./SecretKey
    aes:
      key-path: ./SecretKey
  web:
    jwt:
      secret: ${YUNANEXUS_AUTH_JWT_SECRET}
