spring:
  application:
    name: YunaNexus-UserService # 服务名称
  # 环境激活（Maven自动注入）
  profiles:
    active: @spring.profiles.active@

# MyBatisPlus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cc.nanoic.yunanexus.user.entity
  configuration:
    map-underscore-to-camel-case: true # 下划线转驼峰：开启
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 日志实现类
  global-config:
    db-config:
      id-type: auto

server:
  port: 8100 # 端口
custom:
  time:
    time-zone: Asia/Shanghai