spring:
  application:
    name: YunaNexus-UserService

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cc.nanoic.yunanexus.user.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

yunanexus:
  user:
    route:
      version: 0
