server:
  port: 8000

spring:
  application:
    name: YunaNexus-Gateway
  cloud:
    nacos:
      discovery:
        enabled: true
        register-enabled: false

yunanexus:
  gateway:
    routes:
      auth:
        paths:
          - /auth/**
          - /login/**
          - /register/**
          - /key/**
          - /oauth/**
        service: YunaNexus-AuthService
      user:
        paths:
          - /user/**
          - /me
        service: YunaNexus-UserService