spring:
  application:
    name: YunaNexus-Gateway
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  cloud:
    nacos:
      discovery:
        enabled: true
        register-enabled: true
    gateway:
      server:
        webmvc:
          routes:
            - id: auth-service
              uri: lb://YunaNexus-AuthService
              predicates:
                - Path=/auth/**,/login/**,/register/**,/key/**,/oauth/**,/oauth2/**,/admin/**
            - id: file-avatar
              uri: lb://YunaNexus-FileService
              predicates:
                - Path=/file/avatar/**
            - id: file-service
              uri: lb://YunaNexus-FileService
              predicates:
                - Path=/file/**

yunanexus:
  gateway:
    shard:
      routes:
        - base-name: YunaNexus-UserService
          paths:
            - /user
            - /me
            - /internal/user
        - base-name: YunaNexus-FileService
          paths:
            - /file
          exclude-paths:
            - /file/avatar
