server:
  port: 8000

spring:
  application:
    name: YunaNexus-Gateway
  cloud:
    nacos:
      discovery:
        enabled: true
        register-enabled: false
    gateway:
      server:
        webmvc:
          routes:
            - id: auth-service
              uri: lb://YunaNexus-AuthService
              predicates:
                - Path=/auth/**,/login/**,/register/**,/key/**,/oauth/**
            - id: user-service
              uri: lb://YunaNexus-UserService
              predicates:
                - Path=/user/**,/me/**