spring:
  application:
    name: YunaNexus-FileService
  profiles:
    active: @spring.profiles.active@
  servlet:
    multipart:
      max-file-size: ${YUNANEXUS_FILE_MAX_UPLOAD_SIZE:800MB}
      max-request-size: ${YUNANEXUS_FILE_MAX_REQUEST_SIZE:800MB}

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cc.nanoic.yunanexus.file.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

server:
  port: 8300

custom:
  time:
    time-zone: Asia/Shanghai

yunanexus:
  file:
    upload:
      direct-upload-threshold-bytes: ${YUNANEXUS_FILE_DIRECT_UPLOAD_THRESHOLD_BYTES:524288000}
      normal-user-max-file-size-bytes: ${YUNANEXUS_FILE_NORMAL_USER_MAX_FILE_SIZE_BYTES:2147483648}
      normal-user-max-space-bytes: ${YUNANEXUS_FILE_NORMAL_USER_MAX_SPACE_BYTES:53687091200}
      chunk-size-bytes: ${YUNANEXUS_FILE_CHUNK_SIZE_BYTES:16777216}
      temp-root-path: ${YUNANEXUS_FILE_TEMP_ROOT_PATH:./storage/yunanexus-file-temp}
    storage:
      local:
        root-path: ${YUNANEXUS_FILE_STORAGE_ROOT:./storage/yunanexus-file}
    avatar:
      max-size-bytes: ${YUNANEXUS_FILE_AVATAR_MAX_SIZE_BYTES:5242880}
      allowed-content-types: ${YUNANEXUS_FILE_AVATAR_ALLOWED_CONTENT_TYPES:image/jpeg,image/png,image/webp}
      allowed-extensions: ${YUNANEXUS_FILE_AVATAR_ALLOWED_EXTENSIONS:jpg,jpeg,png,webp}